Yamin/ft login and register
Appitzr-Project/Frontend pull request #104
Opened 2021-05-06 21:33 UTC by agungjati

https://trello.com/c/mcj1z3jT/75-convert-register-page-to-use-fooyes-template-create-register-page-import-register-component
https://trello.com/c/85k5PHpg/65-convert-login-page-to-use-fooyes-template-create-login-page-import-login-component

2021-05-06 21:42 UTC, bagasprakarso approved these changes

2021-05-06 21:43 UTC, bagasprakarso requested changes
Please resolve conflict

2021-05-07 02:32 UTC, JuniYadi approved these changes
LGTM.!

Sukses login dan logout menggunakan email di local meskipun commit nya campur2,tetapi aq liat file changes nya aman ga ke yg lain

2021-05-07 02:38 UTC, bagasprakarso approved these changes

2021-05-07 02:39 UTC, merged