/create tos and pricacy
Appitzr-Project/Frontend pull request #111
Opened 2021-05-11 13:24 UTC by Yamin08

2021-05-11 15:19 UTC, JuniYadi requested changes
1. Rebase dulu
2. Cek Comment ku

2021-05-11 15:19 UTC, JuniYadi commented on src/App.js
> +            <Route path="/privacy" component={Privacy} />
URL yg ini [1]

2021-05-11 15:19 UTC, JuniYadi commented on src/components/Footer/index.jsx
> +              <li><a href="/Privancy">Privacy</a></li>
Harus sama dengan yg ini [1], kalau beda huruf kecil besar, link ga bisa di akses

2021-05-11 21:41 UTC, bagasprakarso requested changes

2021-05-12 01:45 UTC, franky19 commented on src/components/Footer/index.jsx
> +              <li><a href="/Privancy">Privacy</a></li>
a href nya ganti jadi LINK. dan sama kan url yang dituju dengan Route pada app.js

Referensi
https://reactrouter.com/web/guides/quick-start

2021-05-12 04:04 UTC, Yamin08 commented on src/components/Footer/index.jsx
> +              <li><a href="/Privancy">Privacy</a></li>
oke Mas

2021-05-12 04:04 UTC, Yamin08 commented on src/App.js
> +const Privacy = lazy(() => import('./routes/Privacy/index.jsx'))
Sipa mas bagas

2021-05-17 06:10 UTC, closed without merging