Rahmat/new member/menu
Appitzr-Project/Frontend pull request #42
Opened 2021-03-15 18:50 UTC by mrsetiawan

request new branch & create member menu list

2021-03-16 16:40 UTC, bagasprakarso approved these changes

2021-03-16 19:11 UTC, bagasprakarso requested changes

2021-03-16 19:11 UTC, bagasprakarso commented on src/components/Member/OrderMenu/components/MenuCard.js
> +                    href='#'
src/components/Member/OrderMenu/components/MenuCard.js
  Line 131:19:  The href attribute requires a valid value to be accessible. Provide a valid, navigable address as the href value. If you cannot provide a valid href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid

2021-03-17 08:33 UTC, JuniYadi commented
Move to PR #51

2021-03-17 08:33 UTC, closed without merging