Update Menu list screen
Appitzr-Project/Frontend pull request #59
Opened 2021-03-19 17:07 UTC by franky19

1. rapikan tampilan mobile untuk menu list sesuai dengan trello 
    https://www.figma.com/file/ynZ1Tsw0tjL3UcaieDAGbC/Apptizr?node-id=431%3A2

2021-03-19 17:53 UTC, bagasprakarso requested changes

2021-03-19 17:53 UTC, bagasprakarso commented on src/components/Member/OrderHistory/MenuCard.jsx
> +    <Grid
1. font color dan text belum sesuai figma
2. icon heart misplaced
3. gambar tidak full
4. 5. & 6. seharusnya Camel Case
7. Jarak antara completed dan button terlalu jauh, please see figma
8. jarak antara order per tanggal terlalu jauh, see figma

![image](https://user-images.githubusercontent.com/24664561/111822422-5bf4fc80-8916-11eb-9c2c-5a438771882d.png)

2021-03-22 02:27 UTC, franky19 commented on src/components/Member/OrderHistory/MenuCard.jsx
> +    <Grid
on progress

2021-03-25 13:23 UTC, franky19 commented on src/components/Member/OrderHistory/MenuCard.jsx
> +    <Grid
sudah selesai mas bagas atau teman - teman frontend, silahkan dicek dan review jika ada perubahan

2021-03-26 17:39 UTC, bagasprakarso approved these changes

2021-03-27 02:40 UTC, franky19 commented
update tampilan aku pindah ke new branch franky/orderHistory/Menu/Fix pada pull request https://github.com/Appitzr-Project/Frontend/pull/85

2021-03-27 02:40 UTC, closed without merging